apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/component: configmap
data:
  APP_ENV: "development"
  LOG_LEVEL: "debug"
  REPORTS_STORAGE_PATH: "/mnt/reports"
  LOGS_STORAGE_PATH: "/mnt/logs"
  TRIGGER_CRONJOB_NAME: "kraken-trading-job"