apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app.kubernetes.io/component: secret
stringData:
  mongodb-username: "admin"
  mongodb-password: "athena123!"
  external-api-token: "your-api-token"
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/component: configmap
data:
  APP_ENV: "development"
  LOG_LEVEL: "info"
  MONGO_URI: "mongodb://$(mongodb-username):$(mongodb-password)@mongodb-service:27017/app-db"
  REPORTS_STORAGE_PATH: "/mnt/reports"
  LOGS_STORAGE_PATH: "/mnt/logs"