apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app.kubernetes.io/component: secret
stringData:
  mongodb-username: "krakenapp"
  mongodb-password: "athena123!"
  external-api-token: "your-api-token"
  kraken-api-key: "vS7ALvxBJr5b8wl8G9IAMdkP9+f5bW7GIX4ZTX3VVlQnlEhUFD7xDDPT"
  kraken-api-secret: "jrDiOP/ybGpqYXjZdR8eYzFAMPVpNZe+2EFyTwtM/8q8N164yy3lInMW91DG9VW3qXovMsbgC/4h/ewGHyyEtg=="
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/component: configmap
data:
  APP_ENV: "development"
  LOG_LEVEL: "info"
  MONGO_URI: "mongodb://$(mongodb-username):$(mongodb-password)@mongodb-service:27017/app-db"
  REPORTS_STORAGE_PATH: "/mnt/reports"
  LOGS_STORAGE_PATH: "/mnt/logs"