apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-secrets
  labels:
    app.kubernetes.io/component: secret
stringData:
  mongodb-username: "krakenapp"
  mongodb-password: "athena123!"
  kraken-api-key: "vS7ALvxBJr5b8wl8G9IAMdkP9+f5bW7GIX4ZTX3VVlQnlEhUFD7xDDPT"
  kraken-api-secret: "jrDiOP/ybGpqYXjZdR8eYzFAMPVpNZe+2EFyTwtM/8q8N164yy3lInMW91DG9VW3qXovMsbgC/4h/ewGHyyEtg=="
  kraken-api-expiry: "2025-05-30"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/component: configmap
data:
  APP_ENV: "development"
  LOG_LEVEL: "debug"
  REPORTS_STORAGE_PATH: "/mnt/reports"
  LOGS_STORAGE_PATH: "/mnt/logs"
  TRIGGER_CRONJOB_NAME: "kraken-trading-job"