apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: data-tracker
  app.kubernetes.io/part-of: kraken-trading-app
  app.kubernetes.io/managed-by: argocd-kustomize
  environment: development
commonAnnotations:
  managed-by: argocd
  owner: devops-team
  app.kubernetes.io/name: data-tracker
  app.kubernetes.io/part-of: kraken-trading-app
  app.kubernetes.io/managed-by: argocd-kustomize

resources:
- rbac.yaml
- pvc.yaml
- configs.yaml
- deployments.yaml
- jobs.yaml
- fe_deployments.yaml 
- fe_service.yaml
# - ingress.yaml
# - network.yaml
# - observability.yaml
# - probe.yaml