apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-flask-to-mongodb
  namespace: app-namespace
  labels:
    app.kubernetes.io/name: allow-flask-to-mongodb
    app.kubernetes.io/part-of: my-application
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app: mongodb
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: flask-app
      ports:
        - protocol: TCP
          port: 27017
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-mongodb-external-access
  namespace: app-namespace
  labels:
    app.kubernetes.io/name: restrict-mongodb-external-access
    app.kubernetes.io/part-of: my-application
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app: mongodb
  policyTypes:
    - Ingress
  ingress: [] # Denies all external access to MongoDB
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-flask
  namespace: app-namespace
  labels:
    app.kubernetes.io/name: allow-ingress-flask
    app.kubernetes.io/part-of: my-application
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app: flask-app
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0 # Allow public access to Flask
      ports:
        - protocol: TCP
          port: 5000
