# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: trigger-api
#   labels:
#     app: trigger-api
#     app.kubernetes.io/component: trigger-api
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: trigger-api
#   template:
#     metadata:
#       labels:
#         app: trigger-api
#     spec:
#       serviceAccountName: trigger-api-sa
#       containers:
#         - name: trigger-api
#           image: ghcr.io/ottawacloudconsulting/kraken-trigger-api:latest
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 8000
#           resources:
#             requests:
#               memory: "128Mi"
#               cpu: "250m"
#             limits:
#               memory: "256Mi"
#               cpu: "500m"
#           env:
#             - name: TARGET_NAMESPACE
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.namespace
#             - name: CRONJOB_NAME
#               valueFrom:
#                 configMapKeyRef:
#                   name: app-config
#                   key: TRIGGER_CRONJOB_NAME
#             - name: LOG_LEVEL
#               valueFrom:
#                 configMapKeyRef:
#                   name: app-config
#                   key: LOG_LEVEL
#       restartPolicy: Always