apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: development
commonAnnotations:
  managed-by: argocd
  owner: devops-team

resources:
  - ../../base
  - app-secrets-sealed.yaml