name: Docker Image CI

on:
  push:
    branches: [ "feature/mvp" ]
  pull_request:
    branches: [ "main" ]
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kraken-trading-api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from Dockerfile
      id: version
      working-directory: src/api
      run: |
        version=$(grep -i 'LABEL version=' Dockerfile | sed -E 's/.*version="([^"]+)".*/\1/')
        echo "dockerfile_version=$version"
        echo "dockerfile_version=$version" >> $GITHUB_OUTPUT

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ steps.version.outputs.dockerfile_version }}
          type=raw,value=${{ github.sha }}
          
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: src/api
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}